# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://jbrad.github.io/lean/
encoding:         UTF-8

# Custom vars
current_version:  2.0.0
repo:             https://github.com/jbrad/lean

blog:             http://jasonbradley.me
demo:             http://leantheme.co/demo
purchase:         http://leantheme.co/purchase
support:          https://leantheme.zendesk.com