(function($) {
	$(function() {
		
		// Grab the post title
		$('#post-title').text($('#title').val());
		$('#blog-title').text($('#site-title').text());
		
		// If the post title changes, update the preview
		$('#title').keyup(function() {
			$('#post-title').text($(this).val());
		});
		
		// Poll the permalink field and update the preview as it changes
		setInterval(function() {
			if($('#sample-permalink').text().length > 0 && $('#sample-permalink').text().indexOf('http://') === 0) {
				$('#permalink').text($('#sample-permalink').text());
			} // end if
		}, 1000);
		
		// Poll the date field and update the preview as it changes
		setInterval(function() {
			if($('#timestamp > b').text().indexOf('@') !== -1) {	
				$('#date').text($('#timestamp > b').text().split('@')[0]);
			} else {
				$('#date').text($('#todays-date').text());
			} // end if
		}, 1000);
		
		// Update the description preview to match what the user has entered
		updateMetaDescription($, $('#standard_seo_post_meta_description'));
		$('#standard_seo_post_meta_description').keyup(function() {
			updateMetaDescription($, $(this));			
		});
	
	});
})(jQuery);

/**
 * Updates the meta description character count, preview, and keywords that match the title.
 *
 * @params	$		The jQuery function
 * @params	$this	A reference to the meta description field
 */
function updateMetaDescription($, $this) {

	// First, we update the character counter
	$('#character-count').text( 140 - parseInt($this.val().length) );
	
	$('#description').html(getMetaDescription($, $this));
	
	// Bold words in the description that also match the title, ignore case
	var aTitleWords = $.trim($('#post-title').text()).split(' ');
	if(aTitleWords.length > 0 && $.trim(aTitleWords[0]).length > 0) {
	
		if($('#description').html().length > 0) {
		
			for(var i = 0, l = aTitleWords.length; i < l; i++) {	
			
				var sCurrentWord = aTitleWords[i];
	
				// First, normal cases
				$('#description').html(
					//$('#description').html().replace(new RegExp( '\\b' + sCurrentWord + '\\b', 'g'), '<strong>' + sCurrentWord + '</strong>')
				);
				
				// Then lower case
				$('#description').html(
					//$('#description').html().replace(new RegExp('\\b' + sCurrentWord.toLowerCase() + '\\b', 'g'), '<strong>' + sCurrentWord.toLowerCase() + '</strong>')
				);
			
			} // end for
			
		} // end if
		
	} else {
		
		$('#description').html(getMetaDescription($, $this));
		
	} // end if/else

} // end updateMetaDescription

/**
 * Generates a default description to populate in the meta description preview if none has been provided.
 *
 * @params	$		A reference to the jQuery function
 * @params	$this	A reference to the text area that contains the post meta description.
 */
function getMetaDescription($, $this) {
	
	// Update the preview of the description. If the description is empty,
	// then we'll provide a placeholder.
	var sDescription = $this.val();
	if( $.trim(sDescription).length === 0 ) {
	
		/* Translators: This will need to be localized. */
		sDescription = '<em>This description will be automatically generated by search engines unless you add a Meta Description below.</em>';
		
	} // end if
	
	return sDescription;
	
} // end getMetaDescription