/**
 * Removes entry elements from the array.
 *
 * @params	$		A reference to the jQuery function
 * @params	$this	A reference array of words to be cleaned of empty spaces
 * @return  array	The array of words without the whitespace.
 */
function cleanTitle($, words) {
	"use strict";

	var cleanWords, characters;
	cleanWords = [];
	characters = [ '~', '`', '!', '@', '*', '#', '$', '^', '&', '(', ')', '-', '_', '=', '+', '{', '}', '[', ']', ':', "'", '"', '?', ',', '.', '&' ];

	if ( 0 < words.length ) {

		// Illegal: /, %, '<', '>'

		$(words).each(function() {

			( -1 < $.inArray( this, characters ) ) ?
			 	cleanWords.push( $.trim( encodeURIComponent( this ) ) ) :
				cleanWords.push( this.replace(/\W+/g, '' ) );

		});

	} // end if

	return cleanWords;

} // end cleanTitle

/**
 * Generates a default description to populate in the meta description preview if none has been provided.
 *
 * @params	$		A reference to the jQuery function
 * @params	$this	A reference to the text area that contains the post meta description.
 */
function getMetaDescription($, $this) {
	"use strict";

	// Update the preview of the description. If the description is empty, then we'll provide a placeholder.
	var sDescription = $this.val();
	if( $.trim(sDescription).length === 0 ) {

		/* Translators: This will need to be localized. */
		sDescription = '<em>This description will be automatically generated by search engines unless you add a Meta Description below.</em>';

	} // end if

	return sDescription;

} // end getMetaDescription

/**
 * Updates the meta description character count, preview, and keywords that match the title.
 *
 * @params	$		The jQuery function
 * @params	$this	A reference to the meta description field
 */
function updateMetaDescription($, $this) {
	"use strict";

	var oMatch, aTitleWords, aMatches, sCurrentWord, oRegEx, i, l, sCurrentMatch, characters;

	// First, we update the character counter
	$('#character-count').text( 140 - parseInt($this.val().length, 10) );

	// Next, go ahead an populate the description with whatever has been sotred.
	$('#description').html(getMetaDescription($, $this));

	aTitleWords = $.trim($('#post-title').text()).split(' ');
	aTitleWords = cleanTitle( $, aTitleWords );
	aMatches = [];
	characters = [ '~', '`', '!', '@', '*', '#', '$', '^', '&', '(', ')', '-', '_', '=', '+', '{', '}', '[', ']', ':', "'", '"', '?', ',', '.', '&' ];
	if(0 < aTitleWords.length && 0 < $.trim(aTitleWords[0]).length ) {

		// Loop through each of the title words...
		for( i = 0, l = aTitleWords.length; i < l; i++) {

			// Get the current woird in the title and define a regex used to match it.
			sCurrentWord = decodeURIComponent( aTitleWords[i] );

			if ( -1 < $.inArray( sCurrentWord, characters ) && '&' !== sCurrentWord ) {
				aMatches.push( [ sCurrentWord ] );
			} else {

				oRegEx = new RegExp( '\\b' + sCurrentWord + '\\b', 'gi' );

				// If a match has been found, store it in the array of matches
				oMatch = $('#standard_seo_post_meta_description').val().match( oRegEx );
				if( null !== oMatch ) {
					aMatches.push( oMatch );
				} // end if

			} // end if/else

		} // end for

	} else {

		$('#description').html(getMetaDescription($, $this));

	} // end if/else

	// Loop through each of the matches that were found...
	$(aMatches).each(function() {

		// Loop through each of the elements in this array of matches
		for( i = 0, l = this.length; i < l; i++) {

			// Get the current word and define a regular expression based on the current word
			sCurrentMatch = decodeURIComponent( this[i] );

			if ( -1 < $.inArray( sCurrentMatch, characters ) ) {

				// Finally, update the HTML of the description
				$('#description').html(
					$('#description').html().replace( sCurrentMatch, '<strong>' + sCurrentMatch + '</strong>' )
				);

			} else {

				oRegEx = new RegExp( '\\b' + sCurrentMatch + '\\b', 'g' );

				// Finally, update the HTML of the description
				$('#description').html(
					$('#description').html().replace(oRegEx, '<strong>' + sCurrentMatch + '</strong>')
				);

			} // end if/else

		} // end for

	});

} // end updateMetaDescription

(function($) {
	"use strict";

	$(function() {

		// TODO refactor this.
		if( 0 < $('#post-title').length ) {

			// Grab the post title
			$('#post-title').text($('#title').val());
			$('#blog-title').text($('#site-title').text());

			// If the post title changes, update the preview
			$('#title').keyup(function() {
				$('#post-title').text($(this).val());
			});

			// Poll the permalink field and update the preview as it changes
			setInterval(function() {
				if($('#sample-permalink').text().length > 0 && $('#sample-permalink').text().indexOf('http://') === 0) {
					$('#permalink').text($('#sample-permalink').text());
				} // end if
			}, 1000);

			// Poll the date field and update the preview as it changes
			setInterval(function() {
				if($('#timestamp > b').text().indexOf('@') !== -1) {
					$('#date').text($('#timestamp > b').text().split('@')[0]);
				} else {
					$('#date').text($('#todays-date').text());
				} // end if
			}, 1000);

			// Update the description preview to match what the user has entered
			updateMetaDescription($, $('#standard_seo_post_meta_description'));
			$('#standard_seo_post_meta_description').keyup(function() {
				updateMetaDescription($, $(this));
			});

		} // end if

	});
}(jQuery));